/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JjiSignupComp {
        "openSignUpComp": () => Promise<void>;
        "opened": boolean;
        "titl": string;
    }
}
export interface JjiSignupCompCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJjiSignupCompElement;
}
declare global {
    interface HTMLJjiSignupCompElement extends Components.JjiSignupComp, HTMLStencilElement {
    }
    var HTMLJjiSignupCompElement: {
        prototype: HTMLJjiSignupCompElement;
        new (): HTMLJjiSignupCompElement;
    };
    interface HTMLElementTagNameMap {
        "jji-signup-comp": HTMLJjiSignupCompElement;
    }
}
declare namespace LocalJSX {
    interface JjiSignupComp {
        "onFormDataSubmitted"?: (event: JjiSignupCompCustomEvent<{ username: string, email: string, password: string, confirmPassword: string }>) => void;
        "onSignInLinkClick"?: (event: JjiSignupCompCustomEvent<any>) => void;
        "opened"?: boolean;
        "titl"?: string;
    }
    interface IntrinsicElements {
        "jji-signup-comp": JjiSignupComp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jji-signup-comp": LocalJSX.JjiSignupComp & JSXBase.HTMLAttributes<HTMLJjiSignupCompElement>;
        }
    }
}
